[[collection]]
type = "entry"
title = "The Matrix"
subtitle = "1999 · Sci-Fi"

[[collection]]
type = "entry"
title = "Inception"
subtitle = "2010 · Sci-Fi"

[[collection]]
type = "entry"
title = "Interstellar"
subtitle = "2014 · Sci-Fi"
